### ISSUE TITLE
Scala 2.12 support

### ISSUE THREAD

**Issue by ghostdogpr** [tulz-app/laminext#35]
Hi!
Would it be difficult to cross-build for Scala 2.12?
I am considering building a new module for [Caliban Client](https://ghostdogpr.github.io/caliban/docs/client.html) based on Laminext (in particular, `Fetch` and `WebSocket`) for easy Laminar integration, and that would be cool to have.

**Comment by ghostdogpr** [comment]
Just saw on gitter that Laminar might drop 2.12 support later this year, so I guess this is not really useful then. Feel free to close.

**Comment by yurique** [comment]
There's a (test) dependency on a library that I haven't published for 2.12, as it uses some new collection API that are not covered by scala-collection-compat. I made a compat layer there (https://github.com/tulz-app/stringdiff/commit/7ea50a2aacf3da427118a9af331d02480ffc073e) so I can now publish it for 2.12.

But , which will allow me to try publishing laminext for 2.12, but there are similar issues: some of the new collection APIs are used (like the `ArrayDeque` in WebSocket implementation). I'll see if I can do anything about it.

Keep in mind we don't know for how long the upstream (Airstream and Laminar) are going to be published for 2.12 :) (though "till the end of this year at least" is probably a bet safe enough).

**Comment by yurique** [comment]
> Just saw on gitter that Laminar might drop 2.12

What a timing! :)

Does the lack of 2.12 artifacts block you completely?

**Comment by ghostdogpr** [comment]
> Does the lack of 2.12 artifacts block you completely?

No, I can publish that module for 2.13/3 only. I had a problem with IntelliJ where I was forced to use 2.12 overall because one module is an sbt plugin (which is only possible in 2.12) but I found a workaround to tell IntelliJ to use 2.13 on that module only.
