### ISSUE TITLE
Websocket are not working on 0.13.5

### ISSUE THREAD

**Issue by ylaurent** [tulz-app/laminext#49]
Hello,
It took me time to understand as it is the first time I am using this lib (awesome btw, thanks for all the hard work :), but websocket are not working on version 0.13.5, the status never pass the "isConnecting".

I find out that the example are not currently working either:
https://laminext.dev/websocket/example-websocket-echo
give the error 
```
Error(scala.scalajs.js.JavaScriptException: SyntaxError: Failed to construct 'WebSocket': The subprotocol '' is invalid.)
```
which is i guess related to a recent commit.

Switching to 0.13.0 fixed the issue for me

**Comment by yurique** [comment]
@ylaurent thanks so much for reporting this! Yes, this indeed appears to be related to the latest change (which added the second parameter to the native Websocket, which is exactly the subprotocol).

I'll fix this and release the updated version asap.

**Comment by ylaurent** [comment]
nice, thank you very much :) 👍

**Comment by ghostdogpr** [comment]
Woops, my bad. Thanks for the fix @yurique

**Comment by yurique** [comment]
@ghostdogpr no worries! I should have at least checked that the example kept working :) (also, I would have uncommented the websocket-circe example sooner, as well)

**Comment by yurique** [comment]
0.13.6 is [published](https://github.com/tulz-app/laminext/runs/2828953597?check_suite_focus=true), should get to maven central in ~15 min.
